version: 2
jobs:
  build:
    docker:
      - image: chef/chefdk:3.1.0

    environment:
      CIRCLE_WORKING_DIRECTORY: ~/project/test-cookbook

    steps:
      - checkout

      - restore_cache:
          key: berkshelf

      - restore_cache:
          key: chefdk

      - run: git clone https://$GITHUB_TOKEN:x-oauth-basic@github.com/ClouDesire/ci-conf.git test-cookbook/ci-conf

      - run: cd test-cookbook && ./ci-conf/cookbooks/build.sh

      - save_cache:
          key: berkshelf
          paths:
            - ~/.berkshelf

      - save_cache:
          key: chefdk
          paths:
            - ~/.chefdk

      - run: cd test-cookbook && ./ci-conf/cookbooks/test.sh

      - store_artifacts:
          path: /tmp/foodcritic.log
          destination: foodcritic.log

      - store_artifacts:
          path: .kitchen/logs
          destination: kitchen-logs

workflows:
  version: 2
  build:
    jobs:
      - build
