---
platforms:
  - name: ubuntu-16.04
    driver_config:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1604-lts
  - name: ubuntu-18.04
    driver_config:
      image_project: ubuntu-os-cloud
      image_family: ubuntu-1804-lts
  - name: debian-9
    driver_config:
      image_project: debian-cloud
      image_family: debian-9
  #- name: centos-6
  #  driver_config:
  #    image_project: centos-cloud
  #    image_family: centos-6
  - name: centos-7
    driver_config:
      image_project: centos-cloud
      image_family: centos-7
  #- name: rhel-6
  #  driver_config:
  #    image_project: rhel-cloud
  #    image_family: rhel-6
  - name: rhel-7
    driver_config:
      image_project: rhel-cloud
      image_family: rhel-7

suites:
  - name: default
    run_list:
      - recipe[node-exporter-installer::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
